# CSC115 Unit 10.1 - Multidimensional Arrays

* #### **Today**: 
    - 2D/3D arrays
    - Image generation
    
* #### **This Unit**:
    - 2D arrays
    - 3D arrays
    - Intro to images
    - Arrays and functions
    - File reading
    - Exception Handling<br><br>
    
    
* #### **Upcoming**: 
    - Unit 10 **reading** and **PreQuiz** out NOW
    - **PostQuiz 9** today<br><br>

    - ***Coming Soon***
        - **Lab Adv 6 part B** - AI function writing - out
        - **Lab Adv 6 part C** - Final lab - out Monday
        - <a href="https://sdbor.campuslabs.com/eval-home/">IDEA Surveys Out - % BONUS</a><br><br>
        - ***Final Exam***
            - Monday May 4
            - 10-11:50am
            - Room TBD

<br>
<hr>
<br>
    


<center><img src ="https://i.postimg.cc/jqh9H7qD/And-Now-For-Something-Completely-Different-Z8-Wfkuk7-subtitled.jpg" width=50%></center>
    
<br>

<font size=5>**Attendance Quiz Password**:  **********</font>

<br>

<hr>

### Recall Indexing and Slicing 1D Arrays
* Slice uses `[]` and `:`
* `myarray[start:stop:step]`
* indexes and slices can ONLY be integers

In [1]:
import numpy as np

data = np.array( [1, 2, 3] )

print("Indexing")
print("data[0]  ", data[0] )
print("data[1]  ", data[1] )

print("\nSlicing")
print("data[0:2]", data[0:2] )
print("data[1:] ", data[1:] )
print("data[-2:]", data[-2:] )

Indexing
data[0]   1
data[1]   2

Slicing
data[0:2] [1 2]
data[1:]  [2 3]
data[-2:] [2 3]


##### You can visiualize it this way
<center><img src="https://i.postimg.cc/Gm7Ftf0F/09-01-numpy-1d-slicing.png"></center>

<br>

# 2-D & 3-D Arrays in Numpy
As we have seen, NumPy handles arrays quickly and efficiently.
<br>
We can expand our use of NumPy into multiple dimensions - 2D, 3D and beyond

<br>


## Overview:
1. Investigate 2-dimensional array data
2. Investigate 3-dimensional array data
3. Investigate where such data might show up
    - Image creation and image processing

<br>

### Consider

* A "table" of numbers
    - similar to an Excel spreadsheet<br>
    
<center><table>
<tr><td align=center>1</td><td align=center>2</td><td align=center>3</td><td align=center>4</td></tr>
<tr><td align=center>5</td><td align=center>6</td><td align=center>7</td><td align=center>8</td></tr>
<tr><td align=center>9</td><td align=center>10</td><td align=center>11</td><td align=center>12</td></tr></table></center>



   
* How do we construct such a grid (aka Matrix) with NumPy?

In [6]:
import numpy as np
import matplotlib.pyplot as plt

# Create a table of values (commonly referred to as a matrix or 2-D array)
A = np.array([ [1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12] ])

print(A)
print()
print("size with A.size     ", A.size)
print("size with np.size(A) ", np.size(A))
print()
print("shape with A.shape    ", A.shape)
print("shape with np.shape(A)", np.shape(A))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

size with A.size      12
size with np.size(A)  12

shape with A.shape     (4, 3)
shape with np.shape(A) (4, 3)


<br>

### Notes:

- To construct a 2-D array we use **double brackets** on the end
- Then create individual lists (rows) inside that are comma separated
- **OR** we can create a 1D array and `reshape` it right away

In [7]:
# reshape a 1D array
B = np.arange( 1, 10 ).reshape( (3, 3) )
print(B)
print()
print("Size", B.size)
print("Shape", B.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Size 9
Shape (3, 3)


<br>
<br>

## Accessing Elements of a 2D array
We can access individual elements or entire rows/columns using indexing and slicing  
- `A[row,col]` returns the element in the row, col
    - e.g., `A[2,4]` gives us the element in the 3rd row, and 5th column<br><br>
    
- `A[row_slice,col_slice]` slices the matrix using two slices
    - `A[r_start:r_stop:r_step, c_start:c_stop:c_step]`
    - The `:` operator grabs everything in that dimension
    - e.g., `A[2,:]` grabs everything in row 2 (3rd row) and ALL the columns!

In [8]:
# Print whole array
print("Whole array")
print(A)
print()

# Access element A[1,1] 
print("A[1,1]:  ", A[1,1])

# Access the last element in A
print("A[-1,-1]:", A[-1,-1])

Whole array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

A[1,1]:   5
A[-1,-1]: 12


<br>

#### Accessing rows and columns

In [9]:
# Access the second row of A  (over all columns)
print("Row 1:", A[1,:])

# Access the last two elements of the second row of A 
print("Row 1 last 2 items:", A[1,1:3])
print()

# Access the second column of A (over all rows)
print("Col 1:", A[1:3,1])

Row 1: [4 5 6]
Row 1 last 2 items: [5 6]

Col 1: [5 8]


<br>

#### Accessing diagonals, flipping and reverse

In [10]:
# Access all the diagonal elements 
print("Whole array B again:")
print(B)

print("\nDiag:", np.diag(B))

print("\nFlipped:\n", np.flip(B))

print("\nReverse:\n", B[::-1, ::-1])

Whole array B again:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diag: [1 5 9]

Flipped:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Reverse:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


<br>

### Let's look at this graphically

In [11]:
data = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


<center><img src="https://i.postimg.cc/PqMPNpvB/09-01-numpy2d.png" width=500></center>

In [12]:
print( "data[0,1]    ", data[0,1] )
print( "data[1:3]  \n", data[1:3] )
print( "data[0:2,0]  ", data[0:2,0] )

data[0,1]     2
data[1:3]  
 [[3 4]
 [5 6]]
data[0:2,0]   [1 3]


<center><img src="https://i.postimg.cc/G2h9DLk9/09-01-numpy2d-slicing.jpg" width=600></center>

<br><hr><br>

<table border=0 width=100%><tr><td bgcolor="green" align=center><font size=5 color=white><b>You Try</b></td></tr></table>

<br>

#### 1. Make a 2D array of the numbers 11 to 50 in 4 rows of 10 columns. 
* Create the 2D array in one line of code *(hint: generate a 1D array and reshape it)*
* Print it

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr)

<br>

#### 2. Now change it to an array of 5 rows of 8 columns. Print it.

In [ ]:
arr = arr.________(5,8)
print(arr)

<br>

#### 3. Just print:
* The element in the second row and 5th column
* The third row only
* The fourth column only
* The lower right square of 4 items

In [ ]:
print( arr[___,___] )
print( arr[___,___] )
print( arr[___,___] )
print( arr[___,___] )

<br>

<hr>

<br>

## Randomly generated 2D arrays

* Similar to our 1-D arrays, we can use random values to populate 2D arrays

In [ ]:
# Generate a 20 element 1D array of random integers between [0,10]
oneD = np.random.________( 0, 10, 20 )
print(oneD)
print()

<br>

#### With 2D arrays we can just give the size as a tuple
`np.random.randint( low, high-1, (rows, cols) )`

In [ ]:
# Generate a 10 x 10 array of random integers between [0,5]
arr = np.random.randint( 0, 5, ________ ) # size given as a tuple
print(arr)

<hr>

<br>

## Printing (or operating) on all elements of the array

* Because 2-D arrays have 2-dimensions, we normally would need to nest loops to cycle through all of the elements
* Not with NumPy

<br>

### The Non-NumPy way - sum all the elements in a 2D array
* Let's just add up all of the elements in the above array using loops


In [ ]:
# sum all the elements in a 2-D array
print(arr)

# initialize our summation
array_sum = 0

# Get the number of rows and columns of the array
row, col = arr.shape

# loop through all elements indices in the array
for i in range(row):
    for j in range(col):
        array_sum = array_sum + arr[i,j]
        
print("\nThe summation of all elements is:", array_sum)        
        

<br>

### NumPy functions let us do this faster and easier

<br>

##### Sum of all elements

In [ ]:
# the sum of the whole array
sum_arr = np._______(arr)
print("The summation of all elements is:", sum_arr)

<br>

##### Sum of Row 1

In [ ]:
# just the sum of row 1
sum_row1 = np.sum(arr[___,___])
print("The summation of row1 elements is:", sum_row1)

<br>

##### Sum of Column 1

In [ ]:
# just the sum of column 1
sum_col1 = np.sum(arr[___,___]])
print("The summation of column1 elements is:", sum_col1)

<br>

### Just like 1D arrays, arithmetic operators operate on the entire 2D array

In [ ]:
# normalize the array by dividing by the sum
arr_norm = arr / sum_arr

# use np.round to round output
print(np.________(arr_norm, 3))

<br>

### 3D Arrays are very similar but *MUCH* harder to visualize

In [ ]:
# Create a 3-D array of values 
A_3D = np.array([ [ [1,2,3],    [4,5,6] ],         # easier to see
                  [ [7,8,9],    [10,11,12] ], 
                  [ [13,14,15], [16,17,18] ], 
                  [ [19,20,21], [22,23,24] ] ])

print(A_3D)
print()
print("Shape:", A_3D.shape)
print("Size:", A_3D.size)
print("Len:", len(A_3D), "\t<-- DON'T USE" )
print("Sum:", np.sum(A_3D))

<br>

## A reminder about `len` vs `np.size`

#### Use `np.size` with NumPy arrays.
* `np.size` shows how many elements are in the array
* `len` shows the size of the **first dimension** of the array
* in 1D arrays these are the same but not multi-dimensional

In [ ]:
import numpy as np

myarr = np.linspace(4, 500, 400).reshape(40, 10)

print("np.shape:  ", np.shape(myarr) )
print("np.shape[0]", np.shape(myarr)[0] )
print("np.shape[1]", np.shape(myarr)[1] )
print("np.size:   ", np.size(myarr) )
print("len():     ", len(myarr), "\t<-- DON'T USE" )


<hr>

<table border=0 width=100%><tr><td bgcolor="green" align=center><font size=5 color=white><b>You Try</b></td></tr></table>

<br>

### 1. In one step, make a 6 x 5 array of random numbers between 10 and 15 inclusive. 
* Is `np.random.randint` inclusive/exclusive?
* Print it.

In [ ]:
arr = 
print(arr)

<br>

### 2. Reshape the array to be 3 x 10
* print the shape
* print the size

In [ ]:
arr = 
print(arr)



<br>

### 3. What is the mean and sum of the whole array?
* What is the mean and sum of each row?

In [ ]:
print( "sum:", _________ )
print( "mean:", _________ )

print()
print( "sum row 0:", _________ )
print( "mean row 0:", _________ )

print( "sum row 1:", _________ )
print( "mean row 1:", _________ )

print( "sum row 2:", _________ )
print( "mean row 2:", _________ )

print()

<br>

### 4. What is the max values of the array?
* Where are they located?

<br><br><br><br><br><br><br><br>

## Time for a PostQuiz

#### Password: ************