# CSC115 Unit 7.1 - Introduction to NumPy

* #### **Today**:
    - Introduction to NumPy Arrays<br><br>
    
* #### **This Unit**:
    - The NumPy array
    - Benefits of NumPy
    - Built-in methods
    - Iterating
    - 2D arrays<br><br>
    
* #### **Upcoming**: 
    - **Read** Unit 7 reading and do **PreQuiz**
    - **Lab #5** out Friday (due Wednesday 4/8)
    - **PostQuiz 7** Monday`

<br>
<hr>
<br>
    


<center><img src ="https://i.postimg.cc/jqh9H7qD/And-Now-For-Something-Completely-Different-Z8-Wfkuk7-subtitled.jpg" width=50%></center>
    
<br>

<font size=5>**Attendance Quiz Password**:  resting </font>

<br>

<hr>

<center>

## Shameless Plug - **62nd Annual Cultural Expo**

<a href="https://sites.google.com/view/southdakotaminesculturalexpo/cultural-expo"><img src="https://i.postimg.cc/KY05srJj/Cultural_Expo_3.jpg" width=600><br>

### **Saturday March 28 from 11am to 1:30 pm** - </a>
<font size=5>Food<br>
Entertainment<br>
Games</font>

</center>

<br><hr><br>


## Review

* We've now seen:
    - I/O (print & input statements)
    - Variables
    - Math usage
    - Conditionals & Branching
    - Iteration (while and for loops)
    - Functions
    - Sequences like Strings, Lists, and Tuples

<br>

## The Problem with Lists (As Discussed in Unit 7.0)

Lists are powerful datatypes in which we can store multiple types 

If they contain numbers we can perform relatively quick operations using built-in list methods and functions
- Min
- Max
- Sum
- Slicing
- Copy
- Append

<br>

### BUT....What if we want to do math easily and quickly on all elements of a list?
- Add an integer to every element
- Multiply by a value
- Add all the values of two lists together

<br>

#### Example: Multiply every item in a list by 7
>    How can we do this?<br><br>
>    Probably will need a loop

<br>

In [1]:
# multiply 7 to every element in a list

somelist = [3, 5, 1, 2, 7, 88, 34, 24, 34, 121, 234, 6, 7, 8]
num = 7

print( somelist )

# iterate through each element
for i in range( len(somelist) ):
    somelist[i] = somelist[i] * 7      # update the list
    
print(somelist)
    


[3, 5, 1, 2, 7, 88, 34, 24, 34, 121, 234, 6, 7, 8]
[21, 35, 7, 14, 49, 616, 238, 168, 238, 847, 1638, 42, 49, 56]


<br>
<br>
<br>

### But...We can do this really quickly with a new library module called `NumPy`

<img src="https://i.postimg.cc/d1MrNqMm/07-numpy.png">


* Like lists we can also find the:
    - Min (and where the min occurs)
    - Max (and where the max occurs)
    - Sum
    - Mean
    - Standard Deviation
    - etc


In [2]:
# shorthand way of importing NumPy
import numpy as np


somelist = [3, 5, 1, 2, 7, 88, 34, 24, 34, 121, 234, 6, 7, 8]
numpyarray = np.array( somelist )  # make a numpy array from list somelist
num = 7

print( numpyarray )

# multiply the whole array by num
numpyarray = numpyarray * num    # or numpyarray *= num

print( numpyarray )


[  3   5   1   2   7  88  34  24  34 121 234   6   7   8]
[  21   35    7   14   49  616  238  168  238  847 1638   42   49   56]


<br>
<br>

<hr>

# Introduction to NumPy

<center><img src="https://i.postimg.cc/d1MrNqMm/numpy.png"></center>

**NumPy (and it's younger brother SciPy) are the defacto standard for scientific computing in *Python***
  - **NumPy** stands for **Numerical Python**
    - It is a "Library" similar to the `math` or `random` libraries
    - It contains many different routines for performing operations in numerical linear algebra
    - Pronounced *Num-Pie* (not Num-Pee - it rhymes with Dumb-Guy)<br><br>
  - **SciPy** stands for **Scientific Python**
    - It is built on NumPy and provides many different tools for scientific computing

* Information regarding both can be found:
  1. Here for <a href="https://numpy.org">NumPy</a>
  2. Here for <a href="https://www.scipy.org">SciPy</a>

<br><br>

### NumPy arrays

* To begin, we introduce a sequence available in NumPy 
  - **The NumPy array**
  - In NumPy this is called an **nd array** - an <u>n-dimensional array</u><br><br>

<center><img src="https://i.postimg.cc/kgynncM5/07-numpy-array.png" width=400></center>


#### NumPy Alias
* To get started with NumPy (similar to `math` and `random` modules), we need to `import` the tools
  - `import numpy`
  - Because we don't want to type "numpy" every time we use one of the built in methods we use <b>*np*</b> for shorthand
  - At the top of your code listing, type:

    ```python
    import numpy as np
    ``` 
  - To be fair, this doesn't save much typing but it is the way most people use numpy

* Just like that, we're ready to use the power of NumPy to solve problems


#### Let's first have a look at the `NumPy` array, and discuss how it differs from `lists`, `tuples`, and `strings`
  
  
<br>

#### A NumPy example

In [3]:
import numpy as np    # import the NumPy library

# create a list, tuple, and array 
MyList = [ 45, 3.14, "hello" ]            # square brackets
MyTuple = ( 45, 3.14, "hello" )           # round brackets
MyArray = np.array( [45, 3.14, "hello"] ) # round & square  
                                          # np.array() function takes any sequence as an input

<br>

#### We can print the first elements of each sequence using **indices**

In [5]:
print( "First element of list:", MyList[0] )
print( "First element of tuple:", MyTuple[0] ) 
print( "First element of array:", MyArray[0] )


First element of list: 45
First element of tuple: 45
First element of array: 45


<br>

#### Or the last element (or any inbetween)

In [6]:
print( "Last element of list:", MyList[-1] )
print( "Last element of tuple:", MyTuple[-1] ) 
print( "Last element of array:", MyArray[-1] )


Last element of list: hello
Last element of tuple: hello
Last element of array: hello


<br>

#### Or we can print the whole sequence and its `type`

In [7]:
# print their contents
print( MyList )
print( MyTuple )
print( MyArray )

print()  # blank line

# investigate their type
print( type( MyList ) )
print( type( MyTuple ) )
print( type( MyArray ) )

[45, 3.14, 'hello']
(45, 3.14, 'hello')
['45' '3.14' 'hello']

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>


<br>

#### At first glance, they don't look all that different!
* The NumPy array <u>does not</u> have commas separating the elements
* The elements in the NumPy array were all made into one datatype.  What type?

<br>
<br>

### Let's print the datatype of each element of the sequences

In [8]:
# print the type of elements in each sequence

# the list
print( "*****THE LIST*****" )
print( MyList )
print()

print( "The List Content:" )
for i in range( len(MyList) ):
    print( "  ", MyList[i], type( MyList[i] ) )

*****THE LIST*****
[45, 3.14, 'hello']

The List Content:
   45 <class 'int'>
   3.14 <class 'float'>
   hello <class 'str'>


In [9]:

# the tuple
print( "*****THE TUPLE*****" )
print( MyTuple )
print()

print( "The Tuple Content:" )
for i in range( len(MyTuple) ):
    print( "  ", MyTuple[i], type( MyTuple[i] ) )

*****THE TUPLE*****
(45, 3.14, 'hello')

The Tuple Content:
   45 <class 'int'>
   3.14 <class 'float'>
   hello <class 'str'>


In [10]:

# the ndarray
print( "*****THE NUMPY ARRAY*****" )
print( MyArray )
print()

print( "The ND Array Content:" )
for i in range( len(MyArray) ):
    print( "  ", MyArray[i], type( MyArray[i]) )

*****THE NUMPY ARRAY*****
['45' '3.14' 'hello']

The ND Array Content:
   45 <class 'numpy.str_'>
   3.14 <class 'numpy.str_'>
   hello <class 'numpy.str_'>


<br>

### What happened?
- The list and the tuple have what we'd expect: an integer, a float, and a string
-  The NumPy array *ONLY* contains strings (and they are "special" `numpy.str` types)
    - Not much different than "normal" strings<br><br>

* What is going on?
    - Arrays are **homogenous** data structures
    - **IMPORTANT: NumPy arrays can only contain data of the <u>EXACT SAME</u> type!**
    
    - If an array is created with different data types, NumPy will **"promote"** that data to the **most "complex"** type<br><br>

* #### NumPy Order of complexity:
    - strings > floats > ints

<br>
<hr>
<br>

## Create a NumPy array using `np.array` function
- Include both integers and floats

In [11]:
# Create a NumPy array from a list with some integers and floats
NewArray = np.array( [ 1,0.5,6,7,89,101 ] )   # put in values here

print(NewArray)

[  1.    0.5   6.    7.   89.  101. ]


> * Notice that all of the integers now have a decimal behind them
> * This indicates they are now floating point values and no longer integers

In [12]:
# grab the first element in the array and print its data type

print( type( NewArray[0] ) )

<class 'numpy.float64'>


<br>

#### In addition to being a float, NumPy has different **levels** of floats too!!!
- No need to worry too much about this right now.
- It is simply how much accuracy NumPy will use (store) for that variable
    > **Note:** yours may be different ( `numpy.float32` ) depending on your computer!

    > If we absolutly want a specific data type, NumPy does allow us to change things

<br>

#### NumPy supports different sized integers as well. The ones most useful are:
* `int32` - 32 bits, range approximately +/- 2 billion and change
* `int64` - 64 bits, range approximately +/- 9 quintillion
* If you want to know more about NumPy data types go <a href="https://numpy.org/doc/stable/user/basics.types.html">HERE</a>

<br>

### Size and Shape of NumPy arrays
* We've seen that we can print the `type` of an array
* We can also find some useful information about our array:
    - `size`
    - `shape`
    - `number` of dimensions

In [14]:
some2Dlist = [(1, 4, 6, 19), 
              (-34, 3.4, 4, 2), 
              (4, -67.3, 14, 900)]
              
NewArray = np.array( some2Dlist )  # this is a 2D array
print(NewArray)
print()

print( "length =", len( NewArray ) )
print( "size =", np.size(NewArray) )   
print( "shape =", np.shape(NewArray) )
print( "dimensions =", np.ndim(NewArray) )

[[  1.    4.    6.   19. ]
 [-34.    3.4   4.    2. ]
 [  4.  -67.3  14.  900. ]]

length = 3
size = 12
shape = (3, 4)
dimensions = 2


> **Notice:** the `len` doesn't give us the number of elements.  More on this later

<br><br>

<hr>


## Lists vs NumPy Arrays

<center><img src="https://i.postimg.cc/3N0NLvTH/07-01-lists-vs-numpy.jpg" width=400></center>

* So why use NumPy arrays instead of lists?

* **Recall:** when using a list, multiplying the list by a value simply made more <u>copies</u> of the list

<br>

### Example: High and low temperatures over a ten day forecast using Lists
* Calculate the average by adding the lists together and dividing by 2
* We will use the `random.sample` function to make a random list of highs and lows

In [15]:
# make some lists
import random

highs = random.sample( range(35, 90), 10 )  # random sample of 10 highs
lows = random.sample( range(-10, 34), 10 )  # random sample of 10 lows

combined = highs +  lows   # add the lists together

print("highs:", highs)
print("lows:", lows)
print()

print("combo:", combined)


highs: [68, 70, 82, 40, 58, 67, 88, 39, 56, 89]
lows: [8, 31, 10, 25, 22, 27, 11, 15, -3, 16]

combo: [68, 70, 82, 40, 58, 67, 88, 39, 56, 89, 8, 31, 10, 25, 22, 27, 11, 15, -3, 16]


> This doesn't do what we want

<br>

##### If we really wanted to add the values of two lists together we would need a **loop** and a **new list**

In [16]:
# blank list
combined_high_low = []

# iterate through the list
for i in range(len(highs)):
    added = highs[i] + lows[i]
    combined_high_low.append( added )
    
print("new combo:", combined_high_low)

new combo: [76, 101, 92, 65, 80, 94, 99, 54, 53, 105]


<br>

##### What if we want to calculate the **average** of each day in the highs and lows list?

In [17]:
combined_avg = []

for i in range( len(highs) ):
    avg = ( highs[i] + lows[i] ) / len(highs) 
    combined_avg.append( avg )

print("avg:", combined_avg)



avg: [7.6, 10.1, 9.2, 6.5, 8.0, 9.4, 9.9, 5.4, 5.3, 10.5]


> This is a lot of extra work

<br><br>

### Example: The power of the NumPy array
* What happens when we perform the same arithmatic on NumPy arrays?

In [18]:
# imports
import numpy as np
import random

highs = random.sample( range(35, 90), 10 )  # random sample of 10 highs
lows = random.sample( range(-10, 34), 10 )  # random sample of 10 lows

# Convert these lists to NumPy arrays instead
highs_arr = np.array(highs)
lows_arr = np.array(lows)





# Now lets add them together
high_low_arr = highs_arr + lows_arr

print("highs:", highs_arr)
print("lows: ", lows_arr)
print()

print("combo:", high_low_arr)

highs: [56 70 78 36 35 75 82 72 84 63]
lows:  [13 33 12  8 32 19 11 28 -8 18]

combo: [ 69 103  90  44  67  94  93 100  76  81]


> See how this added each element together?
> 
<br>

In [19]:
# And compute our average temperatures (without using a loop!)

avgs_arr = high_low_arr / 2   # this divides every element by 2

print( "avg:", avgs_arr)
print( type(avgs_arr) )
print( type(avgs_arr[0]) )

avg: [34.5 51.5 45.  22.  33.5 47.  46.5 50.  38.  40.5]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


<br><br>

## NumPy Broadcasting

#### Scalar operations applied to a NumPy array are **"broadcast"** to each element of the array.
```text
2 * [3 5 10] = [2*3  2*5  2*10] = [6 10 20]
```

<br>

#### With lists, multiplication replicates a list

In [20]:
# with lists we replicate
mylist = [2, 4, 5, 7, 1, 2, 4, 5]

print("original:", mylist)
print("3 times: ", 3 * mylist)

original: [2, 4, 5, 7, 1, 2, 4, 5]
3 times:  [2, 4, 5, 7, 1, 2, 4, 5, 2, 4, 5, 7, 1, 2, 4, 5, 2, 4, 5, 7, 1, 2, 4, 5]


<br>

#### With NumPy arrays, multiplication **broadcasts** to every element

In [21]:
# with nd arrays we multiply
myarray = np.array(mylist)
print("original:", myarray)

mynewarray = 3 * myarray
print("3 times :", mynewarray)

original: [2 4 5 7 1 2 4 5]
3 times : [ 6 12 15 21  3  6 12 15]


<br>
<hr>
<br>

<table border=0 width=100%><tr><td bgcolor="green" align=center><font size=5 color=white><b>You Try</b></td></tr></table>

#### 0. Import the NumPy library as np
* Yes, we already imported above but this is practice

In [22]:
import numpy as np


<br>

#### 1. Manually create a list of 8 numbers.  Create a NumPy array from this list and print it
* Use the `np.array()` function

In [6]:
import numpy as np
import random
numList = [1, 2, 3, 4, 5, 6, 7, 8]
numArray = np.array( numList )
print(numArray)

[1 2 3 4 5 6 7 8]


<br>

#### 2. Multiply the array from part 1 by 30 and print it

In [7]:
numArray = numArray * 30
print(numArray)


[ 30  60  90 120 150 180 210 240]


<br>

#### 3. Create another NumPy array of 8 numbers.
* Maybe use `random.sample`

In [8]:
randomList = random.sample( range(1, 100), 8 )
randomArray = np.array( randomList )
print(randomArray)



[96 36 26 33 48 78 37 75]


<br>

#### 4. Add these two arrays together and print the result

In [9]:
sumArray = randomArray + numArray
print(sumArray)

[126  96 116 153 198 258 247 315]


<br>

#### 5. Find the average of each element of the two arrays.  
* What datatypes are each element?
* Why?

In [10]:
avgArray = sumArray / 2
print(avgArray)

[ 63.   48.   58.   76.5  99.  129.  123.5 157.5]


<br>

#### 6. What are the size, shape and dimensions of this array?  
* Avoid `len`, use `np.size` instead

In [11]:
size = np.size(avgArray)
shape = np.shape(avgArray)
dimensions = np.ndim(avgArray)
print("size:", size)
print("shape:", shape)
print("dimensions:", dimensions)

size: 8
shape: (8,)
dimensions: 1


<br>

#### 7. CHALLENGE: Can you write the code that will do the same operations for lists?
* Can you start to see why NumPy arrays will be helpful?

In [13]:
sizeNum = np.size(numList)
shapeNum = np.shape(numList)
dimensionsNum = np.ndim(numList)
print("size:", sizeNum)
print("shape:", shapeNum)
print("dimensions:", dimensionsNum)

size: 8
shape: (8,)
dimensions: 1


<br>

# More NumPy to come