# CSC115 Unit 7.2 - NumPy Math and Methods

* #### **Today**:
    - NumPy arrays vs Lists
    - NumPy speed
    - NumPy Math<br><br>
    
* #### **This Unit**:
    - The NumPy array
    - Benefits
    - Built-in methods
    - Iterating
    - 2D arrays<br><br>
    
* #### **Upcoming**: 
    - **Read** Unit 7 reading and do **PreQuiz**
    - **Lab #5** out (due Thursday 4/9)
    - **PostQuiz 7** Monday

    - Unit 8 **reading** and **PreQuiz** out this weekend
      

<br>
<hr>
<br>
    


<center><img src ="https://i.postimg.cc/jqh9H7qD/And-Now-For-Something-Completely-Different-Z8-Wfkuk7-subtitled.jpg" width=50%></center>
    
<br>

<font size=5>**Attendance Quiz Password**:  stunned </font>

<br>

<hr>

<center>

## Shameless Plug - **62nd Annual Cultural Expo**

<a href="https://sites.google.com/view/southdakotaminesculturalexpo/cultural-expo"><img src="https://i.postimg.cc/zfxkPS0f/cultural_expo_2.jpg" width=600><br>

### **Saturday March 28 from 11am to 1:30 pm** - </a>
<font size=5>Food<br>
Entertainment<br>
Games</font>

</center>

<br><hr><br>

## History of NumPy

<img src="https://i.postimg.cc/d1MrNqMm/numpy.png">

* Founded in 2005 by **Travis Oliphant**
* Based on Numeric by Jim Hugunin from 1995
* Was originally part of SciPy but broke away as its own array object library
* Current version 2.4.0 

In [1]:
import numpy as np
print( "numpy version:", np.__version__ )

numpy version: 2.3.5


<br>

## Review NumPy arrays


<br>

#### We can import NumPy library with the following command

In [2]:
import numpy as np

<br>

#### We can create NumPy arrays from any sequence using `np.array`

In [3]:
mylist = [17, 99, 56.8, 35, 567, 223, 198, 77, 100]

mynumpyarray = np.array( mylist )
print( mynumpyarray )

[ 17.   99.   56.8  35.  567.  223.  198.   77.  100. ]


<br>

#### NumPy arrays contain all the same data types.  Data is **promoted** to match

In [4]:
newarray = np.array( [ 'spam', 3, 17.6, 42, 'viking' ] )
print( newarray )

['spam' '3' '17.6' '42' 'viking']


<br>

### Size and Shape of NumPy arrays
* We've seen that we can print the `type` of an array
* We can also find the `size`, `shape`, and `number` of dimensions

In [5]:
nextArray = np.array( [(1, 4, 6, 19), 
                       (-34, 3.4, 4, 2), 
                       (4, -67.3, 14, 900)] )  #2D array
print(nextArray)
print()

print( "elements =", np.size( nextArray ) )   # this is better than len
print( "shape =", np.shape( nextArray ) )
print( "dimensions =", np.ndim( nextArray ) )

[[  1.    4.    6.   19. ]
 [-34.    3.4   4.    2. ]
 [  4.  -67.3  14.  900. ]]

elements = 12
shape = (3, 4)
dimensions = 2


<br>

## A Note about `len` vs `np.size`

#### `len` with NumPy does work but is different than `np.size`
* `np.size` shows how many elements are in the array
* `len` shows the size of the first dimension of the array
* in 1D arrays these are the same but not multi-dimensional

In [6]:
print("np.shape:  ", np.shape(nextArray) )
print("np.size:   ", np.size(nextArray) )
print("len:       ", len(nextArray) )


np.shape:   (3, 4)
np.size:    12
len:        3


#### Break the habit of using `len` now - use `np.size` going forward
> Notice we can make 2D arrays - more on this later

<br><br>

## Lists vs NumPy Arrays

<br>

### Example: Calculate $y$ for $y = 5x^2 - 4x + 2$ for all $x$ values -10 to 10 inclusive
* First calculate $y$ with lists

In [7]:
# make some lists

ylist = []
xlist = list(range(-10, 11))


for x in xlist:
    y = 5 * x ** 2 - 4 * x + 2
    ylist.append(y)

print(ylist)


[542, 443, 354, 275, 206, 147, 98, 59, 30, 11, 2, 3, 14, 35, 66, 107, 158, 219, 290, 371, 462]


<br>

#### The NumPy way
* No loops
* No append
* No problem

In [9]:
import numpy as np

x = np.array(xlist) 
y = 5 * x**2 - 4 * x + 2  # y = 5x^2 - 4x + 2

print(y)
    

[542 443 354 275 206 147  98  59  30  11   2   3  14  35  66 107 158 219
 290 371 462]


<br><br>
<hr><br>

# NumPy vs. Lists: Speed and Size
NumPy arrays are much faster and more efficient than lists.  But how much faster?
<br><br>


### Memory consumption between NumPy array and lists 
In this example, a Python list and a NumPy array of size 100,000,000 will be created. The size of each element and then the whole size of both containers will be calculated and a comparison will be done in terms of memory consumption. 

Reference: *https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/*

In [10]:
# importing NumPy package
import numpy as np
  
# importing system module
import sys

size = 100_000_000

print( f"Comparing memory usage for Lists and NumPy arrays over {size:,} elements" )
print( "-" * 75 )


###################################################
# Lists
###################################################
# declaring a list of 100,000,000 elements
mylist = list( range(size) )
  
# printing size of each element of the list
print( "Size of each element of list in bytes: ", sys.getsizeof(mylist[0]) )
  
# printing size of the whole list
print( f"Size of the whole list in bytes: {sys.getsizeof(mylist[0]) * len(mylist):,}")

print()

###################################################
# NumPy
###################################################
# declaring a NumPy array of 100,000,000 elements

myarray = np.arange(size)
  
# printing size of each element of the NumPy array
print( "Size of each element of the NumPy array in bytes: ", myarray.itemsize )
  
# printing size of the whole NumPy array
print( f"Size of the whole NumPy array in bytes: {myarray.size * myarray.itemsize:,}" )

print()
print( f"That is {sys.getsizeof(mylist[0]) / myarray.itemsize:.2f} times more memory for lists" )

Comparing memory usage for Lists and NumPy arrays over 100,000,000 elements
---------------------------------------------------------------------------
Size of each element of list in bytes:  28
Size of the whole list in bytes: 2,800,000,000

Size of each element of the NumPy array in bytes:  8
Size of the whole NumPy array in bytes: 800,000,000

That is 3.50 times more memory for lists


<br><br>
### Time comparison between NumPy array and Python lists 
In this example, 2 Python lists and 2 NumPy arrays will be created and each container has 100,000,000 elements. 

Multiplication of elements in both the lists and NumPy arrays respectively will be carried out and the difference in time needed for the execution for both the containers will be analyzed to determine which one takes less time to perform the operation.

In [11]:
# importing required packages
import numpy as np
import time
  
# size of arrays and lists
size = 100_000_000

print( f"Comparing timing for Lists and NumPy arrays over {size:,} elements" )
print( "-" * 75 )
  
# declaring lists
list1 = list( range(size) )
list2 = list ( range(size) )

  
# declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)
  
# capturing time before the multiplication of Python lists
initialTime1 = time.perf_counter()
  
# multiplying elements of both the lists and stored in another list
resultantList = [ (a * b) for a, b in zip(list1, list2) ]
  
# calculating execution time
endTime = time.perf_counter()
time1 = endTime - initialTime1
print( "Lists multiplication time:", time1, "seconds" )
  
# capturing time before the multiplication of NumPy arrays
initialTime2 = time.perf_counter()

# multiplying elements of both the NumPy arrays and stored in another NumPy array
resultantArray = array1 * array2
  
# calculating execution time
endTime = time.perf_counter()
time2 = endTime - initialTime2

print()
print( "NumPy Arrays multiplication time:", time2 , "seconds" )

print()
print( f"That is {time1 / time2:.2f} times more time for lists" )



Comparing timing for Lists and NumPy arrays over 100,000,000 elements
---------------------------------------------------------------------------
Lists multiplication time: 14.357327500008978 seconds

NumPy Arrays multiplication time: 5.073142099980032 seconds

That is 2.83 times more time for lists


<br><br>

### Conclusion
**Advantages of using NumPy Arrays Over Python Lists:**
* Consumes less memory.
* Fast as compared to the python List.
* Convenient to use.

### May need to restart your kernel here

<hr>

<br>

# More NumPy Math

* We can perform math operations that are consistant with linear algebra
  - vector addition
  - vector subtraction
  - scalar multiplication
  - scalar division<br><br>


### Recall:

#### Vector addition: adding the x, y and z components separately

<center><img src="https://mathinsight.org/media/image/image/vector_parallelogram_law.png" width=25%></center>

Given two vectors $a$ and $b$:<br>
<center>

$a = [1,2,3]$ and $b = [4,5,6]$

</center>

* We can add and subtract them (assuming they are of the same length) by simply adding and subtracting their elements

$$
c = a + b = [1,2,3]+[4,5,6] =[5,7,9]
$$
$$
d = a - b = [1,2,3]-[4,5,6] = [-3,-3,-3]
$$

* We can multiply and divide by scalars by multiplying or dividing the scalar with each element

$$
c = 2a = 2 \cdot[1,2,3] = [2,4,6]
$$
$$
d = b/4 = \frac{1}{4}\cdot[4,5,6] = [1, \frac{5}{4},\frac{3}{2}]
$$


<br>

### Vector Addition and Subtraction with NumPy

In [12]:
import numpy as np

# In code 
a = np.array( [1, 2, 3] )
b = np.array( [4, 5, 6] )

print("Addition:")
print(a, "+", b, "=", a + b)
print()

print("Subtraction")
print(a, "-", b, "=", a - b)
print()

print("Scalar Multiplication")
print(2, "*", a, "=", 2 * a)
print()

print("Scalar Division")
print(b, "/ 4 =", b / 4)


Addition:
[1 2 3] + [4 5 6] = [5 7 9]

Subtraction
[1 2 3] - [4 5 6] = [-3 -3 -3]

Scalar Multiplication
2 * [1 2 3] = [2 4 6]

Scalar Division
[4 5 6] / 4 = [1.   1.25 1.5 ]


<br>

### Multiplying and Dividing Arrays
* You can multiply and divide two **equal-sized** arrays.
* The operations are carried out among corresponding elements of the two arrays.

In [13]:
# using array a and b from above

print("Array Multiplication")
print(a, "*", b, "=", a * b)
print()

print("Array Division")
print(a, "/", b, "=", a / b)

Array Multiplication
[1 2 3] * [4 5 6] = [ 4 10 18]

Array Division
[1 2 3] / [4 5 6] = [0.25 0.4  0.5 ]


<br>

## So how do we concatenate a NumPy array?
* **Recall:** multiplying a list by 2 simply <u>replicates</u> the list twice
    * Similarly, adding two lists simply concatenated them into a single list
    
* How do we do similar operations with arrays?
    > We will use NumPy's randint function `np.random.randint( low, high, number )`<br> 
    > NOTE: low is inclusive, but high is <font color=red>exclusive</font>

In [14]:
# create two random arrays (we can use one of several random number generators)
import numpy as np

# using NumPy's randint function - 5 numbers -100 to 100 inclusive
a = np.random.randint(-100, 101, 5)  
b = np.random.randint(-100, 101, 5) 

# print our arrays
print("a = ", a)
print("b = ", b)
print()

a =  [-13 -46 -94  59  68]
b =  [ 94  90  17  41 -79]



##### List concatenation does not work here

In [15]:
# List concatenation operators don't work 
print("Trying list concatenation operators")
print("3 * a = ", 3 * a)
print("a + b = ", a + b)
print()

Trying list concatenation operators
3 * a =  [ -39 -138 -282  177  204]
a + b =  [ 81  44 -77 100 -11]



> That doesn't concatenate like we want<br><br>

#### Use the `np.concatenate` function

In [16]:
# Instead, we must use a np method 
print("Using np.concatenate method")

c = np.column_stack( (a, a, a) )
print("3 * a = ", c)

c = np.concatenate( (a, b) )
print("a + b = ", c)
print()

Using np.concatenate method
3 * a =  [[-13 -13 -13]
 [-46 -46 -46]
 [-94 -94 -94]
 [ 59  59  59]
 [ 68  68  68]]
a + b =  [-13 -46 -94  59  68  94  90  17  41 -79]



#### We can also "stack" rows, columns or tables
* `hstack` concatenates horizontally - a longer row, just like `np.concatenate`
* `vstack` concatenates vertically - another row below

In [17]:
# Can also "stack" the arrays
# horizontal stacking
d = np.hstack( (a, a) )
print("hstack\n", d)
print()

# vertical stacking 
e = np.vstack( (a, a) )
print("vstack\n", e) # What's happening here???? (more later)

hstack
 [-13 -46 -94  59  68 -13 -46 -94  59  68]

vstack
 [[-13 -46 -94  59  68]
 [-13 -46 -94  59  68]]


<br>

## NumPy Math tools
NumPy provides a rich set of math tools
- **IMPORTANT**: Anytime we want to do math on a **whole array**, we need to use the `np` version<br><br>
    - The `import math` and `math.` version WILL NOT work <br><br>
- We have many methods/functions like:<br><br>
    ```python
    np.abs(array)
    np.sqrt(array)
    np.floor(array)

    np.max(array)
    np.min(array)
    np.sort(array)
    np.mean(array)
    np.std(array)

    np.pi
    np.sin(array)
    np.cos(array)
    np.tan(array)
    np.arcsin(array)
    np.arctan(array)
    ```
- There are other functions:<br><br>
    ```Python
    np.reshape( row, col )
    np.where( b==0 )
    ```
- There are also matrix, linear algebra, polynomial, and statistical routines<br><br>
- Find more <a href="https://numpy.org/doc/stable/reference/routines.math.html">HERE</a>


<br>

##### Try `math` library with NumPy arrays
* This will give an error

In [20]:
# using NumPy functions on an array
angle_arr = np.random.randint(-45, 46, 100)

angle_arr_rad = np.radians(angle_arr)
cos_arr = np.cos(angle_arr_rad)

print(cos_arr)

[0.9781476  0.93358043 0.98768834 0.99939083 0.98480775 0.80901699
 0.94551858 0.7313537  0.9612617  0.96592583 0.8480481  0.76604444
 0.92050485 0.97437006 0.93969262 0.96592583 0.70710678 0.7313537
 0.77714596 0.98162718 0.76604444 0.99026807 0.83867057 0.99939083
 1.         0.77714596 0.9781476  0.74314483 0.78801075 0.82903757
 0.82903757 0.82903757 0.74314483 0.9961947  0.81915204 0.76604444
 0.98162718 0.74314483 0.93969262 0.79863551 0.9781476  0.87461971
 0.9781476  0.94551858 0.9961947  0.9945219  0.80901699 0.99026807
 0.9781476  0.82903757 0.91354546 0.76604444 0.83867057 0.99254615
 0.74314483 0.8660254  0.9781476  0.9961947  0.97437006 0.91354546
 0.8571673  0.9998477  0.99862953 0.90630779 0.9612617  0.8480481
 0.87461971 0.8480481  0.88294759 0.99026807 0.78801075 0.99862953
 0.98162718 0.95105652 0.70710678 0.94551858 0.98162718 0.92718385
 0.93358043 0.93358043 0.99254615 0.92050485 0.7193398  0.89879405
 0.8480481  0.98768834 0.79863551 0.99939083 0.89879405 0.857167

##### Only use **NumPy versions** of functions on NumPy arrays

In [21]:
# try with NumPy functions
angle_arr = np.random.randint(-45, 46, 100)

angle_arr_rad = np.radians(angle_arr)  # np.radians
cos_arr = np.cos(angle_arr_rad)        # np.cos

print(cos_arr)

[0.9612617  0.7313537  0.91354546 0.91354546 0.8480481  0.98480775
 0.99862953 0.76604444 0.93969262 0.9945219  0.92050485 0.93969262
 0.98162718 0.70710678 1.         0.97029573 0.89879405 0.88294759
 0.8571673  0.98480775 0.78801075 0.99254615 0.9998477  0.92050485
 0.95630476 0.75470958 0.81915204 0.9781476  0.9612617  0.80901699
 0.98480775 0.7193398  0.79863551 0.89879405 0.75470958 0.78801075
 1.         0.75470958 0.92050485 0.99862953 0.92050485 0.90630779
 0.92050485 0.7313537  0.99862953 0.9781476  0.95105652 0.99756405
 0.74314483 0.89100652 0.98162718 0.94551858 0.75470958 0.76604444
 0.70710678 0.7313537  0.99254615 0.74314483 0.78801075 0.70710678
 0.99254615 0.9961947  0.93358043 0.9781476  0.9998477  0.90630779
 0.99026807 0.93969262 0.97437006 0.98480775 0.8571673  0.88294759
 0.9998477  0.9961947  0.98480775 0.96592583 0.93358043 0.8660254
 0.95105652 0.99756405 0.8571673  0.9998477  0.9945219  0.89879405
 0.74314483 0.74314483 0.92718385 0.89100652 0.80901699 0.90630

<br>

## We can reshape our arrays

#### Reshaping Two Ways
* `arrayname.reshape( dimensions )`
* `np.reshape( arrayname, dimensions )`

In [24]:
zarr = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9] )
print(zarr)
print("shape:", np.reshape(zarr, (3,3)).shape)
print()

print("arrayname.reshape as 3x3 array")
y = zarr.reshape( 3,3 )
print(y)

[1 2 3 4 5 6 7 8 9]
shape: (3, 3)

arrayname.reshape as 3x3 array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
zarr = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9] )
print(zarr)
print("shape:", zarr.reshape(3,3).shape)
print()

print("np.reshape as 3x3 array")
y = np.reshape(zarr, (3,3))
print(y)

[1 2 3 4 5 6 7 8 9]
shape: (3, 3)

np.reshape as 3x3 array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Why **multiple ways** to do the same thing?
* Matlab and R

<br>

#### Some `NumPy` math operations

In [27]:
# basic math operations 
a = np.random.randint( 100, size=(10) )  # Generate 10 random integers between [0,100)
print( "a = ", a )

print() 

print( "np.max =", np.max(a) )
print( "max at index:", np.argmax(a))
print( "np.min =", np.min(a) )
print( "min at index:", np.argmin(a))


a =  [18 71  2  6 92 46 34 25 50 49]

np.max = 92
max at index: 4
np.min = 2
min at index: 2


In [28]:
print( "np.sqrt =", np.sqrt(a) )

np.sqrt = [4.24264069 8.42614977 1.41421356 2.44948974 9.59166305 6.78232998
 5.83095189 5.         7.07106781 7.        ]


In [29]:
# new array 
b = np.array( [1, -1, -5, 0, -4, 0] )
print( "b =", b )

print()

print( "np.abs =", np.abs(b) )
print( "np.sort =", np.sort(b) )

b = [ 1 -1 -5  0 -4  0]

np.abs = [1 1 5 0 4 0]
np.sort = [-5 -4 -1  0  0  1]


<br>

##### `np.where`
A very powerful function that creates an array of locations "where" something occurs
* i.e. where all values are > 10

**Find indexes where all values less than 0 occur**

In [30]:
print(b)
loc = np.where( b < 0 )  # locates indices of any values < 0 in b

print( "np.where(b < 0) =", loc )   

[ 1 -1 -5  0 -4  0]
np.where(b < 0) = (array([1, 2, 4]),)


**What are the array values at these indexes?**

In [31]:
print( "b where < 0 =", b[loc] )  # array of all values where b is < 0

b where < 0 = [-1 -5 -4]


**Modify only the values less than 0**

In [32]:
print(b)

b[loc] = 10

print(b)

[ 1 -1 -5  0 -4  0]
[ 1 10 10  0 10  0]


<hr>
<br>
<br>



## More NumPy next time